[package]
name = "gbc-claim"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
alloy = "1.0.30"
